api_platform:
    title: Hello API Platform of Mciré
    version: 1.0.0
    eager_loading:
        fetch_partial: true
    defaults:
        pagination_client_enabled: true
        pagination_client_items_enabled: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
               
