api_platform:
    title: Bienvenu sur l'API de devfinder
    version: 1.0.0
    eager_loading:
        fetch_partial: true
    
    formats:
        # outputFormats and inputs formats configuration:
        jsonld: ['application/json+ld']
        json: ['application/json']
        # jsonl: [' application/merge-patch+json']
        # multipart: ['application/x-www-form-urlencoded', 'application/merge-patch+json']

    docs_formats:
        jsonld: ['application/json+ld']
        # json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_client_enabled: true
        pagination_client_items_enabled: true
    enable_swagger: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    
    description: 'README ~ Les end-point sont structuré de la manière suivante: [  Nom du module - Nom de lacteur qui intervient dans ce module ] '

