vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        projets:
            uri_prefix: /fichiers/projets
            upload_destination: '%kernel.project_dir%/public/fichiers/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        briefs:
            uri_prefix: /fichiers/briefs
            upload_destination: '%kernel.project_dir%/public/fichiers/briefs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        immersions:
            uri_prefix: /fichiers/immersions
            upload_destination: '%kernel.project_dir%/public/fichiers/immersions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
