controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /connexion
    methods: ['POST']
    
app_logout:
    path: 
        en: /api/logout
        fr: /deconnexion
    methods: ['POST']

