controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /api/connexion
    methods: ['POST']
    
app_logout:
    path:
        /api/deconexion
    methods: ['POST']

app_refresh:
    path: /api/token/refresh
    
