name: CD
on:
  push:
    branches: 
      - develop 
      - feature/f6-testUnitaire
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'
    
      - name: Install dependencies
        run: composer install

      - name: Debug project location
        run: |
          ls -la
          
      - name: Change permissions of bootstrap.php
        run: |
          chmod +r /home/runner/work/DevFinder/DevFinder/tests/bootstrap.php

      - name: Run Unit tests
        run: php bin/phpunit
        
