name: CI

on:
  push:
    branches:
      - develop
      - feature/f6-testUnitaire

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: php:8.1.2-apache

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: pass_test
          MYSQL_DATABASE: myapptest
          MYSQL_USER: myapptest
          MYSQL_PASSWORD: pass_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DATABASE_URL: 'mysql://myapptest:pass_test@localhost:3306/myapptest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git libzip-dev
          curl -sS https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
          docker-php-ext-install mysqli pdo pdo_mysql zip
          composer install

      - name: Set up MySQL
        run: |
          php bin/console doctrine:database:drop --force --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:fixtures:load --no-interaction

      - name: Run PHPUnit tests
        run: php bin/phpunit

 
