name: CI

on:
  push:
    branches:
      - develop
      - feature/f6-testUnitaire
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker MySQL container
      run: docker run --name mysql-container -d -p 3306:3306 MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:5.7

    - name: Wait for MySQL to be ready
      run: sleep 30

    - name: Install Composer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git libzip-dev
        curl -sS https://getcomposer.org/installer | php -- --disable-tls
        sudo mv composer.phar /usr/local/bin/composer
        composer install --no-scripts
    
    - name : See docker staus
      run: docker ps
    
    
    - name: Grant privileges to MySQL user
      run: |
          docker start mysql-container
          docker logs mysql-container

          docker start mysql-container
          docker exec mysql-container mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.17.0.1' IDENTIFIED BY '' WITH GRANT OPTION;"
          docker exec mysql-container mysql -uroot -e "FLUSH PRIVILEGES;"
      
    - name: Configure and prepare database
      run: |
        cp .env.test .env.local
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:migrations:migrate --env=test
        php bin/console doctrine:fixtures:load --env=test --no-interaction

    - name: Run functional tests
      run: php bin/phpunit
