name: CI

on:
  push:
    branches:
      - develop
      - feature/f6-testUnitaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git libzip-dev
          curl -sS https://getcomposer.org/installer | php -- --disable-tls
          mv composer.phar /usr/local/bin/composer
          docker-php-ext-install mysqli pdo pdo_mysql zip

      - name: Set up MySQL
        run: |
          docker run --name mysql-container -d -p 3306:3306 \
            -e MYSQL_ROOT_PASSWORD=pass_test \
            -e MYSQL_DATABASE=myapptest \
            -e MYSQL_USER=myapptest \
            -e MYSQL_PASSWORD=pass_test \
            mysql:5.7

      - name: Prepare database
        run: |
          php bin/console doctrine:database:drop --force --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:fixtures:load --no-interaction

      - name: Install Composer dependencies
        run: composer install

      # - name: Start PHP server
      #   run: php artisan serve &

      # - name: Run PHPUnit tests
      #   run: php bin/phpunit

    # allow_failure: false
