name: CI
on:
  push:
    branches:
      - develop
      - feature/f6-testUnitaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'

      - name: Install dependencies
        run: composer install

      # - name: Debug project location
      #   run: |
      #     ls -la
      
      # - name: change directory in to test
      #   run: |
      #       cd Tests

      # - name: show in test
      #   run: |
      #     ls -la
      # - name: Change permissions of bootstrap.php
      #   run: | 
      #     chmod -R +r /home/runner/work/DevFinder/DevFinder/tests/bootstrap.php
      - name: Set up Database
        run: |
          php bin/console doctrine:database:create  --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Run Unit tests
        run:  php bin/phpunit 
        # --bootstrap test/bootstrap.php

      # Ajoutez une action pour envoyer une notification en cas d'échec des tests
      - name: Notify on test failure
        if: failure()
        run: echo "Les tests ont échoué. Veuillez vérifier les résultats."
        