name: CI
on:
  push:
    branches:
      - develop
      - feature/f6-testUnitaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'

      - name: Install dependencies
        run: composer install

      - name: Create database
        run: php bin/console doctrine:database:create --if-not-exists --env=test
      
      - name: Migrate in env test
        run:
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
      
      - name: Run fixtures
        run:
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Run Unit tests
        run:  php bin/phpunit 
    
      - name: Notify on test failure
        if: failure()
        run: echo "Les tests ont échoué. Veuillez vérifier les résultats."
        