name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-18.04
    environment: dev
    env: 
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Display variables
        run: echo "APP_USER=${{ secrets.APP_USER }} APP_HOST=${{ secrets.APP_HOST }}"

      - name: Git workflow configuration
        run: echo " git stash" 
          echo " git stash pop" 


      - name: Deploy
        run: |
          sshpass -e ssh -v -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "cd public_html/ && git pull origin master --force"
          git stash
          composer install
          php bin/console doctrine:migrations:migrate -n 
