name: CD
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env: 
      SSHPASS: ${{ secrets.APP_USER }}

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: deploy
        run: 
          sshpass -p 'Deploy999' ssh -o StrictHostKeyChecking=no deploy@159.203.166.191
          "cd public_html/ && git pull"
          # sshpass -e ssh -o stricthostkeychecking=no deploy@159.203.166.191
          # composer install &&
          # php bin/console d:m:m -n"