name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-18.04
    environment: dev
    env:
      SSHPASS: ${{ secrets.APP_PASS }}
      PROJECT_PATH: "/home/1203757.cloudwaysapps.com/sfcastmajs"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run: |
          sudo apt update
          sudo apt install -y sshpass

      - name: Display variables
        run: echo "APP_USER=${{ secrets.APP_USER }} APP_HOST=${{ secrets.APP_HOST }}"

      # - name: Set permissions on migrations
      #   run: chmod -R 755 migrations/ 

      # - name: Clean old migrations
      #   run: |
      #     rm -rf migrations/*

      - name: Deploy
        run: |
          sshpass -e ssh -v -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "cd public_html/ && git pull origin master --force"
      - name: Install composer

        run: |
          composer install --no-scripts 
          
      - name: set permissions on the repository project
        run: |
          chmod -R 755 ${{ env.PROJECT_PATH }} 

      - name: Make migration
        run: |
          php bin/console doctrine:migrations:migrate -n 
          
        #  php bin/console doctrine:migrations:dump-schema
        # php bin/console doctrine:migrations:diff

      # - name: After deployment jwt key publish 
      #   run: |
      #     ./jwt-instal.sh 
      #     chmod 600 var/jwt/private.pem
      #     chmod 644 var/jwt/public.pem 